### ISSUE TITLE
Not working. "Error serializing package 'inline-messenger' TypeError: Cannot read property 'serialize' of undefined"

### ISSUE THREAD

**Issue by asmundstavdahl** [mdgriffith/atom-inline-messenger#9]
This message appears in the log
- after package installation,
- on Atom restart and
- when a message should have been shown.

Atom 1.10.2
Ubuntu 16.04.1

``` js
/usr/share/atom/resources/app.asar/src/package.js:625 Error serializing package 'inline-messenger' TypeError: Cannot read property 'serialize' of undefined
    at Object.module.exports.Messenger.serialize (/home/asmund/.atom/packages/inline-messenger/lib/inline-messenger.coffee:80:35)
    at Package.module.exports.Package.serialize (/usr/share/atom/resources/app.asar/src/package.js:622:100)
    at PackageManager.module.exports.PackageManager.serializePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:596:63)
    at PackageManager.module.exports.PackageManager.serialize (/usr/share/atom/resources/app.asar/src/package-manager.js:589:14)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:782:38)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:994:25
    at AtomEnvironment.module.exports.AtomEnvironment.saveState (/usr/share/atom/resources/app.asar/src/atom-environment.js:988:14)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:314:28
    module.exports.Package.serialize @ /usr/share/atom/resources/app.asar/src/package.js:625
    module.exports.PackageManager.serializePackage @ /usr/share/atom/resources/app.asar/src/package-manager.js:596
    module.exports.PackageManager.serialize @ /usr/share/atom/resources/app.asar/src/package-manager.js:589
    module.exports.AtomEnvironment.serialize @ /usr/share/atom/resources/app.asar/src/atom-environment.js:782
    (anonymous function) @ /usr/share/atom/resources/app.asar/src/atom-environment.js:994
    module.exports.AtomEnvironment.saveState @ /usr/share/atom/resources/app.asar/src/atom-environment.js:988
    (anonymous function) @ /usr/share/atom/resources/app.asar/src/atom-environment.js:314
```

**Comment by vanboom** [comment]
I patched this in my version by adding the `if @messageView` line... hope this helps see line 79 of inline-messenger.coffee

``` coffeescript
 serialize: ->
    if @messageView
      messageViewState: @messageView.serialize()
```
